baseURL = "https://fma0x.github.io/"
title = "fma0x"
paginate = 5
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true

# [languages.en]
# languageName = "English"
# weight = 1
#
#   [languages.en.taxonomies]
#   category = "categories"
#   tag = "tags"
#   series = "series"
#
# [[languages.en.menu.main]]
# name = "Archive"
# url = "archives"
# weight = 5
#
# [[languages.en.menu.main]]
# name = "Search"
# url = "search/"
# weight = 10
#
# [[languages.en.menu.main]]
# name = "Tags"
# url = "tags/"
# weight = 10
#
# [[languages.en.menu.main]]
# name = "WiKi"
# url = "https://github.com/adityatelange/hugo-PaperMod/wiki/"
#
# [[languages.en.menu.main]]
# name = "Discord"
# url = "https://discord.gg/ahpmTvhVmp"
#
# [languages.fr]
# languageName = ":fr:"
# languageAltTitle = "French"
# weight = 2
# title = "PaperModL2"
#
#   [languages.fr.taxonomies]
#   category = "FRcategories"
#   tag = "FRtags"
#   series = "FRseries"
#
#   [languages.fr.profileMode]
#   enabled = true
#   title = "PaperMod"
#   imageUrl = "https://raw.githubusercontent.com/twitter/twemoji/master/assets/svg/1f317.svg"
#   imageTitle = "ProfileMode image"
#   subtitle = "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
#
#     [[languages.fr.profileMode.buttons]]
#     name = "Blog"
#     url = "posts"
#
#     [[languages.fr.profileMode.buttons]]
#     name = "Profile Mode"
#     url = "https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode"
#
# [[languages.fr.menu.main]]
# name = "Archive"
# url = "archives/"
# weight = 5
#
# [[languages.fr.menu.main]]
# name = "FRTags"
# url = "frtags"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "FRCategories"
# url = "frcategories"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "FRSeries"
# url = "frseries"
# weight = 10
#
# [[languages.fr.menu.main]]
# name = "NullLink"
# url = "#"
#
# [languages.fa]
# languagedirection = "rtl"
# weight = 3
# title = "PaperMod RTL"
#
#   [languages.fa.homeInfoParams]
#   Title = "Hi there 👋"
#   Content = "Welcome to RTL layout"
#
#   [languages.fa.taxonomies]
#   category = "FAcategories"
#   tag = "FAtags"
#   series = "FAseries"
#
# [[languages.fa.menu.main]]
# name = "FATags"
# url = "fatags"
# weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "site pessoal"
author = "paulo giovani"
defaultTheme = "dark"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  #Title = "fma0x"
  Content = """
Olá, sou **Paulo Giovani** e este é meu site pessoal.
- Aqui é o meu espaço para compartilhar minhas ideias, opiniões e criações.
- Possuo formações em administração, filosofia e tecnologia. 
- Se lhe interessar conteúdo em vídeo, acesse meu canal no [YouTube](https://youtube.com/@fma0x).
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/fma0x"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@fma0x"

  [[params.socialIcons]]
  name = "x"
  url = "https://x.com/fma0x"

  [[params.socialIcons]]
  name = "codeberg"
  url = "https://codeberg.org/fma0x"

  # [params.editPost]
  # URL = "https://github.com/fma0x/fma0x.github.io/"
  # Text = "Suggest Changes"
  # appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

