baseURL = 'https://fma0x.github.io/'
languageCode = 'pt-BR'
title = 'fma0x'
theme = "PaperMod"

[Params]
  [profileMode]
    enabled = true
    title = "PaperMod"
  [homeInfoParams]
    Title = "oi"
    Content = "uiu uiui"

[Author]
name = "Paulo Giovani"
github = "fma0x"
